export default function loadData() {
  return [
    {
      id: 1,
      amount: 10,
      createdAt: new Date('01/01/2020'),
      customer: 'Matheus Alexandre',
      name: 'Oportunidade Matheus Alexandre 1',
      kanbam: 'new',
      kanbamOrder: 0,
    },
    {
      id: 2,
      amount: 10,
      createdAt: new Date('01/01/2020'),
      customer: 'Matheus Alexandre',
      name: 'Oportunidade Matheus Alexandre 2',
      kanbam: 'new',
      kanbamOrder: 1,
    },
    {
      id: 3,
      amount: 10,
      createdAt: new Date('01/01/2020'),
      customer: 'Matheus Alexandre',
      name: 'Oportunidade Matheus Alexandre 3',
      kanbam: 'new',
      kanbamOrder: 2,
    },
    {
      id: 4,
      amount: 10,
      createdAt: new Date('01/01/2020'),
      customer: 'Matheus Alexandre',
      name: 'Oportunidade Matheus Alexandre 4',
      kanbam: 'contacted',
      kanbamOrder: 0,
    },
    {
      id: 5,
      amount: 10,
      createdAt: new Date('01/01/2020'),
      customer: 'Matheus Alexandre',
      name: 'Oportunidade Matheus Alexandre 5',
      kanbam: 'contacted',
      kanbamOrder: 1,
    },
    {
      id: 6,
      amount: 10,
      createdAt: new Date('01/01/2020'),
      customer: 'Matheus Alexandre',
      name: 'Oportunidade Matheus Alexandre 6',
      kanbam: 'sent',
      kanbamOrder: 0,
      status: 5,
    },
    {
      id: 7,
      amount: 10,
      createdAt: new Date('01/01/2020'),
      customer: 'Matheus Alexandre',
      name: 'Oportunidade Matheus Alexandre 7',
      kanbam: 'sent',
      kanbamOrder: 1,
      status: 6,
    },
  ];
}
